name: Build
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - run: yarn install --immutable --immutable-cache --check-cache
      - id: test
        run: yarn test
      - uses: coverallsapp/github-action@v1
        with:
          git-branch: ${{ github.event.pull_request.head.ref }}
          git-commit: ${{ github.event.pull_request.head.sha }}