name: Build
on:
  push:
    branches:
      - main
  pull_request:

env:
  CODECOV_TOKEN: ${ secrets.CODECOV_TOKEN }

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - run: yarn install --immutable --immutable-cache --check-cache
      - id: test
        run: yarn test
      - uses: codecov/codecov-action@v3